url: "https://hoonyss.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Seong Sihoon (성시훈)" # the name of your site, e.g. ACME Corp.
description: "M.S. student in Chung-Ang university"

# Analytics
analytics:
  provider               : "google-gtag" 
                          # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "G-8HXJWNRLTM"
    anonymize_ip         : # true, false (default)
